#include "lj_ast.h"
namespace LJ {
	char *GetExpressionTypeString(int type)
	{
		switch (type) {
		case BOOLEAN_EXPRESSION: return "BOOLEAN_EXPRESSION";
		case INT_EXPRESSION: return "INT_EXPRESSION";
		case DOUBLE_EXPRESSION: return "DOUBLE_EXPRESSION";
		case STRING_EXPRESSION: return "STRING_EXPRESSION";
		case IDENTIFIER_EXPRESSION: return "IDENTIFIER_EXPRESSION";
		case ASSIGN_EXPRESSION: return "ASSIGN_EXPRESSION";
		case ADD_EXPRESSION: return "ADD_EXPRESSION";
		case SUB_EXPRESSION: return "SUB_EXPRESSION";
		case MUL_EXPRESSION: return "MUL_EXPRESSION";
		case DIV_EXPRESSION: return "DIV_EXPRESSION";
		case MOD_EXPRESSION: return "MOD_EXPRESSION";
		case EQ_EXPRESSION: return "EQ_EXPRESSION";
		case NE_EXPRESSION: return "NE_EXPRESSION";
		case GT_EXPRESSION: return "GT_EXPRESSION";
		case GE_EXPRESSION: return "GE_EXPRESSION";
		case LT_EXPRESSION: return "LT_EXPRESSION";
		case LE_EXPRESSION: return "LE_EXPRESSION";
		case LOGICAL_AND_EXPRESSION: return "LOGICAL_AND_EXPRESSION";
		case LOGICAL_OR_EXPRESSION: return "LOGICAL_OR_EXPRESSION";
		case MINUS_EXPRESSION: return "MINUS_EXPRESSION";
		case EXCLAMATION_EXPRESSION: return "EXCLAMATION_EXPRESSION";
		case FUNCTION_CALL_EXPRESSION: return "FUNCTION_CALL_EXPRESSION";
		case TRUE_EXPRESSION: return "TRUE_EXPRESSION";
		case FALSE_EXPRESSION: return "FALSE_EXPRESSION";
		case NULL_EXPRESSION: return "NULL_EXPRESSION";
		}

		return "EXPRESSION_ERROR";
	}
}
